<?php

session_start();

include "config.php";


/* =========================================================
   FPDF
========================================================= */

require_once __DIR__ . "/fpdf186/fpdf.php";


/* =========================================================
   LOGIN CHECK
========================================================= */

if (!isset($_SESSION['staff_id'])) {
    exit("Unauthorized access.");
}

$staff_id = $_SESSION['staff_id'];


/* =========================================================
   REPORT SETTINGS
========================================================= */

$report_type = $_GET['report_type'] ?? 'task';

$from_date = $_GET['from_date'] ?? date('Y-m-01');

$to_date = $_GET['to_date'] ?? date('Y-m-d');


$allowed_reports = [
    'task',
    'attendance',
    'overtime'
];

if (!in_array($report_type, $allowed_reports)) {
    $report_type = 'task';
}


/* =========================================================
   STAFF INFORMATION
========================================================= */

$stmt = $conn->prepare("
    SELECT
        staff.*,
        supervisors.fullname AS supervisor_name
    FROM staff
    LEFT JOIN supervisors
        ON staff.supervisor_id = supervisors.supervisor_id
    WHERE staff.staff_id = ?
");

$stmt->bind_param(
    "s",
    $staff_id
);

$stmt->execute();

$result = $stmt->get_result();

if ($result->num_rows === 0) {
    exit("Staff member not found.");
}

$staff = $result->fetch_assoc();

$stmt->close();


$fullname =
    $staff['fullname'];

$department =
    $staff['department'] ?? '';

$supervisor_name =
    $staff['supervisor_name']
    ?? 'Not Assigned';


/* =========================================================
   REPORT TITLE
========================================================= */

if ($report_type === 'task') {

    $report_title = "Task Report";

} elseif ($report_type === 'attendance') {

    $report_title = "Attendance Report";

} else {

    $report_title = "Overtime Report";

}


/* =========================================================
   PDF CLASS
========================================================= */

class StaffReportPDF extends FPDF
{

    function Header()
    {
        global $app;
        global $report_title;

        $this->SetFont(
            'Arial',
            'B',
            16
        );

        $this->Cell(
            0,
            10,
            $app['organization_name'],
            0,
            1,
            'C'
        );


        $this->SetFont(
            'Arial',
            'B',
            13
        );

        $this->Cell(
            0,
            8,
            $report_title,
            0,
            1,
            'C'
        );


        $this->Ln(3);
    }


    function Footer()
    {
        $this->SetY(-15);

        $this->SetFont(
            'Arial',
            '',
            8
        );

        $this->Cell(
            0,
            10,
            'Generated by Personnel Timesheet Management System',
            0,
            0,
            'C'
        );
    }


    function TableHeader($headers, $widths)
    {
        $this->SetFont(
            'Arial',
            'B',
            9
        );

        foreach ($headers as $i => $header) {

            $this->Cell(
                $widths[$i],
                8,
                $header,
                1,
                0,
                'C'
            );

        }

        $this->Ln();
    }
}


/* =========================================================
   CREATE PDF
========================================================= */

$pdf = new StaffReportPDF(
    'L',
    'mm',
    'A4'
);

$pdf->SetAutoPageBreak(
    true,
    20
);

$pdf->AddPage();


/* =========================================================
   STAFF INFORMATION
========================================================= */

$pdf->SetFont(
    'Arial',
    '',
    10
);


$pdf->Cell(
    40,
    7,
    'Staff Name:',
    0,
    0
);

$pdf->Cell(
    70,
    7,
    $fullname,
    0,
    0
);


$pdf->Cell(
    35,
    7,
    'Staff ID:',
    0,
    0
);

$pdf->Cell(
    50,
    7,
    $staff_id,
    0,
    1
);


$pdf->Cell(
    40,
    7,
    'Department:',
    0,
    0
);

$pdf->Cell(
    70,
    7,
    $department,
    0,
    0
);


$pdf->Cell(
    35,
    7,
    'Supervisor:',
    0,
    0
);

$pdf->Cell(
    50,
    7,
    $supervisor_name,
    0,
    1
);


$pdf->Cell(
    40,
    7,
    'Period:',
    0,
    0
);

$pdf->Cell(
    100,
    7,
    date(
        "d M Y",
        strtotime($from_date)
    )
    . " - " .
    date(
        "d M Y",
        strtotime($to_date)
    ),
    0,
    1
);


$pdf->Ln(5);


/* =========================================================
   TASK REPORT
========================================================= */

if ($report_type === 'task') {

    $stmt = $conn->prepare("
        SELECT
            report_date,
            start_time,
            end_time,
            hours_worked,
            tasks_completed,
            status
        FROM task_reports
        WHERE staff_id = ?
        AND report_date BETWEEN ? AND ?
        ORDER BY report_date DESC, created_at DESC
    ");

    $stmt->bind_param(
        "sss",
        $staff_id,
        $from_date,
        $to_date
    );

    $stmt->execute();

    $result = $stmt->get_result();


    $headers = [
        'Date',
        'Task',
        'Start',
        'End',
        'Hours',
        'Status'
    ];

    $widths = [
        25,
        145,
        25,
        25,
        25,
        30
    ];


    $pdf->TableHeader(
        $headers,
        $widths
    );


    $pdf->SetFont(
        'Arial',
        '',
        8
    );


    $total_hours = 0;

    $records = 0;


    while ($row = $result->fetch_assoc()) {

        $records++;

        $total_hours +=
            (float)$row['hours_worked'];


        $date =
            date(
                "d M Y",
                strtotime(
                    $row['report_date']
                )
            );


        $start =
            !empty($row['start_time'])
            ? date(
                "h:i A",
                strtotime(
                    $row['start_time']
                )
            )
            : '-';


        $end =
            !empty($row['end_time'])
            ? date(
                "h:i A",
                strtotime(
                    $row['end_time']
                )
            )
            : '-';


        $task =
            $row['tasks_completed'];


        /*
         * Handle multiline task text.
         */

        $task = str_replace(
            "\r",
            '',
            $task
        );


        $pdf->Cell(
            25,
            8,
            $date,
            1
        );


        $pdf->Cell(
            145,
            8,
            substr($task, 0, 85),
            1
        );


        $pdf->Cell(
            25,
            8,
            $start,
            1
        );


        $pdf->Cell(
            25,
            8,
            $end,
            1
        );


        $pdf->Cell(
            25,
            8,
            number_format(
                (float)$row['hours_worked'],
                2
            ),
            1,
            0,
            'C'
        );


        $pdf->Cell(
            30,
            8,
            $row['status'],
            1
        );


        $pdf->Ln();

    }


    $pdf->Ln(5);


    $pdf->SetFont(
        'Arial',
        'B',
        10
    );


    $pdf->Cell(
        60,
        8,
        'Total Task Reports: ' . $records,
        0
    );


    $pdf->Cell(
        60,
        8,
        'Total Hours: ' .
        number_format(
            $total_hours,
            2
        ) . ' h',
        0
    );

}


/* =========================================================
   ATTENDANCE REPORT
========================================================= */

elseif ($report_type === 'attendance') {

    $stmt = $conn->prepare("
        SELECT
            date,
            time_in,
            time_out,
            clock_in,
            clock_out,
            status
        FROM attendance
        WHERE staff_id = ?
        AND date BETWEEN ? AND ?
        ORDER BY date DESC
    ");

    $stmt->bind_param(
        "sss",
        $staff_id,
        $from_date,
        $to_date
    );

    $stmt->execute();

    $result = $stmt->get_result();


    $headers = [
        'Date',
        'Clock In',
        'Clock Out',
        'Hours',
        'Status'
    ];

    $widths = [
        40,
        45,
        45,
        35,
        45
    ];


    $pdf->TableHeader(
        $headers,
        $widths
    );


    $pdf->SetFont(
        'Arial',
        '',
        9
    );


    $total_hours = 0;

    $total_days = 0;

    $total_overtime = 0;


    while ($row = $result->fetch_assoc()) {

        $time_in =
            $row['time_in']
            ?: $row['clock_in'];


        $time_out =
            $row['time_out']
            ?: $row['clock_out'];


        $day_hours = 0;


        if (
            !empty($time_in) &&
            !empty($time_out)
        ) {

            $start =
                strtotime($time_in);

            $end =
                strtotime($time_out);


            if ($end > $start) {

                $day_hours =
                    ($end - $start)
                    / 3600;


                $total_hours +=
                    $day_hours;


                if ($day_hours > 8) {

                    $total_overtime +=
                        $day_hours - 8;

                }

            }

        }


        if (
            strtolower(
                $row['status']
            ) === 'present'
        ) {

            $total_days++;

        }


        $pdf->Cell(
            40,
            8,
            date(
                "d M Y",
                strtotime($row['date'])
            ),
            1
        );


        $pdf->Cell(
            45,
            8,
            !empty($time_in)
                ? date(
                    "h:i A",
                    strtotime($time_in)
                )
                : '-',
            1
        );


        $pdf->Cell(
            45,
            8,
            !empty($time_out)
                ? date(
                    "h:i A",
                    strtotime($time_out)
                )
                : '-',
            1
        );


        $pdf->Cell(
            35,
            8,
            number_format(
                $day_hours,
                2
            ),
            1,
            0,
            'C'
        );


        $pdf->Cell(
            45,
            8,
            $row['status'],
            1
        );


        $pdf->Ln();

    }


    $pdf->Ln(5);

    $pdf->SetFont(
        'Arial',
        'B',
        10
    );


    $pdf->Cell(
        55,
        8,
        'Days Present: ' .
        $total_days,
        0
    );


    $pdf->Cell(
        60,
        8,
        'Total Hours: ' .
        number_format(
            $total_hours,
            2
        ) . ' h',
        0
    );


    $pdf->Cell(
        60,
        8,
        'Overtime: ' .
        number_format(
            $total_overtime,
            2
        ) . ' h',
        0
    );

}


/* =========================================================
   OVERTIME REPORT
========================================================= */

elseif ($report_type === 'overtime') {

    $stmt = $conn->prepare("
        SELECT
            work_date,
            hours_worked,
            overtime_hours,
            status
        FROM timesheets
        WHERE staff_id = ?
        AND work_date BETWEEN ? AND ?
        AND overtime_hours > 0
        ORDER BY work_date DESC
    ");

    $stmt->bind_param(
        "sss",
        $staff_id,
        $from_date,
        $to_date
    );

    $stmt->execute();

    $result = $stmt->get_result();


    $headers = [
        'Date',
        'Regular Hours',
        'Overtime Hours',
        'Total Hours',
        'Status'
    ];

    $widths = [
        40,
        45,
        50,
        45,
        45
    ];


    $pdf->TableHeader(
        $headers,
        $widths
    );


    $pdf->SetFont(
        'Arial',
        '',
        9
    );


    $total_hours = 0;

    $total_overtime = 0;

    $records = 0;


    while ($row = $result->fetch_assoc()) {

        $records++;


        $hours =
            (float)$row['hours_worked'];


        $overtime =
            (float)$row['overtime_hours'];


        $regular =
            $hours - $overtime;


        $total_hours +=
            $hours;


        $total_overtime +=
            $overtime;


        $pdf->Cell(
            40,
            8,
            date(
                "d M Y",
                strtotime(
                    $row['work_date']
                )
            ),
            1
        );


        $pdf->Cell(
            45,
            8,
            number_format(
                $regular,
                2
            ) . ' h',
            1,
            0,
            'C'
        );


        $pdf->Cell(
            50,
            8,
            number_format(
                $overtime,
                2
            ) . ' h',
            1,
            0,
            'C'
        );


        $pdf->Cell(
            45,
            8,
            number_format(
                $hours,
                2
            ) . ' h',
            1,
            0,
            'C'
        );


        $pdf->Cell(
            45,
            8,
            $row['status'],
            1
        );


        $pdf->Ln();

    }


    $pdf->Ln(5);


    $pdf->SetFont(
        'Arial',
        'B',
        10
    );


    $pdf->Cell(
        60,
        8,
        'Records: ' . $records,
        0
    );


    $pdf->Cell(
        65,
        8,
        'Total Hours: ' .
        number_format(
            $total_hours,
            2
        ) . ' h',
        0
    );


    $pdf->Cell(
        65,
        8,
        'Total Overtime: ' .
        number_format(
            $total_overtime,
            2
        ) . ' h',
        0
    );

}


/* =========================================================
   OUTPUT PDF
========================================================= */

$filename =
    "Staff_" .
    ucfirst($report_type) .
    "_Report_" .
    date("Y-m-d") .
    ".pdf";


$pdf->Output(
    'D',
    $filename
);

exit;