<?php
session_start();
include "config.php";

/*
=========================================================
STAFF MONTHLY REPORT - EXCEL EXPORT
=========================================================

This file exports the same monthly report generated by:

staff_monthly_report.php

Features:
- All Staff or selected staff
- Selected month
- Daily records
- Clock In
- Clock Out
- Hours Worked
- Overtime
- Status
- Monthly summary
- Printed By
- Supervisor ID
- Date
- Time

No PhpSpreadsheet required.
=========================================================
*/


/* =====================================================
   CHECK SUPERVISOR LOGIN
===================================================== */

if (!isset($_SESSION['supervisor_id'])) {
    header("Location: supervisor_login.php");
    exit();
}


$supervisor_id = $_SESSION['supervisor_id'];

$fullname = $_SESSION['fullname'] ?? 'Supervisor';


/* =====================================================
   GET FILTERS
===================================================== */

$staff_filter = $_GET['staff_id'] ?? 'all';

$month = $_GET['month'] ?? date('Y-m');


/* =====================================================
   VALIDATE MONTH
===================================================== */

if (!preg_match('/^\d{4}-\d{2}$/', $month)) {
    $month = date('Y-m');
}


$month_start = $month . '-01';

$month_end = date(
    'Y-m-t',
    strtotime($month_start)
);


/* =====================================================
   SUPERVISOR INFORMATION
===================================================== */

$stmt_supervisor = $conn->prepare("
    SELECT
        supervisor_id,
        fullname
    FROM supervisors
    WHERE supervisor_id = ?
    LIMIT 1
");


if (!$stmt_supervisor) {
    die("Supervisor query failed: " . $conn->error);
}


$stmt_supervisor->bind_param(
    "s",
    $supervisor_id
);

$stmt_supervisor->execute();

$supervisor_result =
    $stmt_supervisor->get_result();


if ($supervisor_result->num_rows > 0) {

    $supervisor =
        $supervisor_result->fetch_assoc();

    $fullname =
        $supervisor['fullname'];

    $supervisor_id =
        $supervisor['supervisor_id'];
}


$stmt_supervisor->close();


/* =====================================================
   GET STAFF
===================================================== */

$staff_members = [];


if ($staff_filter === 'all') {

    /*
    -----------------------------------------------------
    ALL STAFF UNDER THIS SUPERVISOR
    -----------------------------------------------------
    */

    $stmt = $conn->prepare("
        SELECT
            staff_id,
            fullname,
            department,
            position
        FROM staff
        WHERE supervisor_id = ?
        AND status = 'Active'
        ORDER BY fullname ASC
    ");

    if (!$stmt) {
        die("Staff query failed: " . $conn->error);
    }

    $stmt->bind_param(
        "s",
        $supervisor_id
    );

} else {

    /*
    -----------------------------------------------------
    SELECTED STAFF
    -----------------------------------------------------
    */

    $stmt = $conn->prepare("
        SELECT
            staff_id,
            fullname,
            department,
            position
        FROM staff
        WHERE supervisor_id = ?
        AND staff_id = ?
        AND status = 'Active'
        LIMIT 1
    ");

    if (!$stmt) {
        die("Staff query failed: " . $conn->error);
    }

    $stmt->bind_param(
        "ss",
        $supervisor_id,
        $staff_filter
    );
}


$stmt->execute();

$result = $stmt->get_result();


while ($row = $result->fetch_assoc()) {

    $staff_members[] = $row;
}


$stmt->close();


/* =====================================================
   SECURITY CHECK
===================================================== */

if ($staff_filter !== 'all' && count($staff_members) === 0) {

    die("Invalid staff selection or staff member does not belong to you.");
}


/* =====================================================
   GENERATE EXCEL FILE
===================================================== */

$filename =
    'Staff_Monthly_Report_' .
    date('F_Y', strtotime($month_start)) .
    '_' .
    date('Ymd_His') .
    '.xls';


/* =====================================================
   EXCEL HEADERS
===================================================== */

header(
    "Content-Type: application/vnd.ms-excel; charset=UTF-8"
);

header(
    "Content-Disposition: attachment; filename=\"$filename\""
);

header("Pragma: no-cache");

header("Expires: 0");


/* =====================================================
   HTML EXCEL DOCUMENT
===================================================== */

echo '<!DOCTYPE html>';

echo '<html>';

echo '<head>';

echo '<meta charset="UTF-8">';


echo '<style>

body {
    font-family: Arial, sans-serif;
    font-size: 12px;
}

.title {
    font-size: 18px;
    font-weight: bold;
    text-align: center;
}

.subtitle {
    font-size: 14px;
    font-weight: bold;
    text-align: center;
}

.period {
    text-align: center;
    font-size: 12px;
}

.staff-heading {
    background-color: #1f4e78;
    color: #ffffff;
    font-size: 14px;
    font-weight: bold;
}

.staff-info {
    background-color: #d9eaf7;
    font-weight: bold;
}

th {
    background-color: #d9e1f2;
    font-weight: bold;
    border: 1px solid #000000;
    padding: 6px;
}

td {
    border: 1px solid #cccccc;
    padding: 5px;
}

.summary-header {
    background-color: #70ad47;
    color: #ffffff;
    font-weight: bold;
}

.summary {
    background-color: #e2f0d9;
    font-weight: bold;
}

.present {
    background-color: #e2f0d9;
}

.absent {
    background-color: #fce4d6;
}

.offday {
    background-color: #eeeeee;
}

.footer {
    font-weight: bold;
}

</style>';

echo '</head>';

echo '<body>';


/* =====================================================
   REPORT HEADER
===================================================== */

echo '<table border="0" width="100%">';

echo '<tr>';

echo '<td colspan="9" class="title">';

echo htmlspecialchars(
    $app['organization_name'] ?? 'NTISHOR WEB ENTERPRISE'
);

echo '</td>';

echo '</tr>';


echo '<tr>';

echo '<td colspan="9" class="subtitle">';

echo 'STAFF MONTHLY REPORT';

echo '</td>';

echo '</tr>';


echo '<tr>';

echo '<td colspan="9" class="period">';

echo 'Month: ' .
    date(
        'F Y',
        strtotime($month_start)
    );

echo '</td>';

echo '</tr>';


echo '</table>';


echo '<br>';


/* =====================================================
   LOOP THROUGH STAFF
===================================================== */

foreach ($staff_members as $staff) {

    $staff_id = $staff['staff_id'];

    $staff_name = $staff['fullname'];

    $department = $staff['department'] ?? '';

    $position = $staff['position'] ?? '';


    /* =================================================
       STAFF HEADING
    ================================================= */

    echo '<table border="0" width="100%">';

    echo '<tr>';

    echo '<td colspan="9" class="staff-heading">';

    echo 'Staff: ' .
        htmlspecialchars($staff_name);

    echo '</td>';

    echo '</tr>';


    echo '<tr>';

    echo '<td class="staff-info">Staff ID</td>';

    echo '<td class="staff-info">' .
        htmlspecialchars($staff_id) .
        '</td>';

    echo '<td class="staff-info">Department</td>';

    echo '<td class="staff-info">' .
        htmlspecialchars($department) .
        '</td>';

    echo '<td class="staff-info">Position</td>';

    echo '<td class="staff-info">' .
        htmlspecialchars($position) .
        '</td>';

    echo '<td colspan="3"></td>';

    echo '</tr>';

    echo '</table>';


    echo '<br>';


    /* =================================================
       TABLE HEADER
    ================================================= */

    echo '<table border="1" width="100%" cellspacing="0" cellpadding="5">';

    echo '<tr>';

    echo '<th>Date</th>';

    echo '<th>Day</th>';

    echo '<th>Clock In</th>';

    echo '<th>Clock Out</th>';

    echo '<th>Hours Worked</th>';

    echo '<th>Overtime</th>';

    echo '<th>Status</th>';

    echo '<th>Late</th>';

    echo '<th>Early</th>';

    echo '</tr>';


    /* =================================================
       MONTHLY VARIABLES
    ================================================= */

    $total_working_days = 0;

    $days_present = 0;

    $days_absent = 0;

    $total_hours = 0;

    $total_overtime = 0;


    /* =================================================
       GET NUMBER OF DAYS
    ================================================= */

    $days_in_month =
        (int)date(
            't',
            strtotime($month_start)
        );


    /* =================================================
       LOOP THROUGH EVERY DAY
    ================================================= */

    for (
        $day = 1;
        $day <= $days_in_month;
        $day++
    ) {

        $current_date =
            date(
                'Y-m-d',
                strtotime(
                    $month_start .
                    ' +' .
                    ($day - 1) .
                    ' days'
                )
            );


        $day_name =
            date(
                'l',
                strtotime($current_date)
            );


        /* =============================================
           WEEKEND CHECK
        ============================================= */

        $is_weekend =
            in_array(
                $day_name,
                ['Saturday', 'Sunday']
            );


        /* =============================================
           GET TIMESHEET FOR THIS DAY
        ============================================= */

        $stmt_time = $conn->prepare("
            SELECT
                clock_in,
                clock_out,
                hours_worked,
                overtime_hours,
                status,
                late_arrival,
                early_departure
            FROM timesheets
            WHERE staff_id = ?
            AND work_date = ?
            ORDER BY id DESC
            LIMIT 1
        ");


        if (!$stmt_time) {
            die(
                "Timesheet query failed: " .
                $conn->error
            );
        }


        $stmt_time->bind_param(
            "ss",
            $staff_id,
            $current_date
        );


        $stmt_time->execute();


        $time_result =
            $stmt_time->get_result();


        $record =
            $time_result->fetch_assoc();


        $stmt_time->close();


        /* =============================================
           DEFAULT VALUES
        ============================================= */

        $clock_in = '';

        $clock_out = '';

        $hours_worked = 0;

        $overtime = 0;

        $late = 0;

        $early = 0;

        $status = '';


        /* =============================================
           IF RECORD EXISTS
        ============================================= */

        if ($record) {

            $clock_in =
                $record['clock_in'] ?? '';

            $clock_out =
                $record['clock_out'] ?? '';

            $hours_worked =
                (float)(
                    $record['hours_worked'] ?? 0
                );

            $overtime =
                (float)(
                    $record['overtime_hours'] ?? 0
                );

            $late =
                (int)(
                    $record['late_arrival'] ?? 0
                );

            $early =
                (int)(
                    $record['early_departure'] ?? 0
                );


            /*
            ---------------------------------------------
            STATUS
            ---------------------------------------------
            */

            if (!empty($clock_in)) {

                $status = 'Present';

            } elseif (!$is_weekend) {

                $status = 'Absent';

            } else {

                $status = 'Off Day';
            }

        } else {

            /*
            ---------------------------------------------
            NO RECORD
            ---------------------------------------------
            */

            if ($is_weekend) {

                $status = 'Off Day';

            } else {

                $status = 'Absent';
            }
        }


        /* =============================================
           COUNT WORKING DAYS
        ============================================= */

        if (!$is_weekend) {

            $total_working_days++;

            if ($status === 'Present') {

                $days_present++;

            } else {

                $days_absent++;
            }
        }


        /* =============================================
           TOTALS
        ============================================= */

        $total_hours +=
            $hours_worked;

        $total_overtime +=
            $overtime;


        /* =============================================
           ROW CLASS
        ============================================= */

        if ($status === 'Present') {

            $row_class = 'present';

        } elseif ($status === 'Absent') {

            $row_class = 'absent';

        } else {

            $row_class = 'offday';
        }


        /* =============================================
           FORMAT TIMES
        ============================================= */

        $formatted_clock_in = '-';

        $formatted_clock_out = '-';


        if (!empty($clock_in)) {

            $formatted_clock_in =
                date(
                    'h:i A',
                    strtotime($clock_in)
                );
        }


        if (!empty($clock_out)) {

            $formatted_clock_out =
                date(
                    'h:i A',
                    strtotime($clock_out)
                );
        }


        /* =============================================
           OUTPUT ROW
        ============================================= */

        echo '<tr class="' .
            $row_class .
            '">';


        echo '<td>';

        echo date(
            'd M Y',
            strtotime($current_date)
        );

        echo '</td>';


        echo '<td>';

        echo htmlspecialchars(
            $day_name
        );

        echo '</td>';


        echo '<td>';

        echo htmlspecialchars(
            $formatted_clock_in
        );

        echo '</td>';


        echo '<td>';

        echo htmlspecialchars(
            $formatted_clock_out
        );

        echo '</td>';


        echo '<td>';

        echo number_format(
            $hours_worked,
            2
        ) . ' h';

        echo '</td>';


        echo '<td>';

        echo number_format(
            $overtime,
            2
        ) . ' h';

        echo '</td>';


        echo '<td>';

        echo htmlspecialchars(
            $status
        );

        echo '</td>';


        echo '<td>';

        echo $late
            ? 'Yes'
            : 'No';

        echo '</td>';


        echo '<td>';

        echo $early
            ? 'Yes'
            : 'No';

        echo '</td>';


        echo '</tr>';
    }


    /* =================================================
       CLOSE DAILY TABLE
    ================================================= */

    echo '</table>';


    echo '<br>';


    /* =================================================
       AVERAGE HOURS
    ================================================= */

    $average_hours = 0;


    if ($days_present > 0) {

        $average_hours =
            $total_hours /
            $days_present;
    }


    /* =================================================
       MONTHLY SUMMARY
    ================================================= */

    echo '<table border="1" width="100%" cellspacing="0" cellpadding="5">';


    echo '<tr>';

    echo '<td colspan="6" class="summary-header">';

    echo 'MONTHLY SUMMARY';

    echo '</td>';

    echo '</tr>';


    echo '<tr>';


    echo '<th>Total Working Days</th>';

    echo '<th>Days Present</th>';

    echo '<th>Days Absent</th>';

    echo '<th>Total Hours Worked</th>';

    echo '<th>Total Overtime</th>';

    echo '<th>Average Hours Per Day</th>';


    echo '</tr>';


    echo '<tr class="summary">';


    echo '<td>';

    echo $total_working_days;

    echo '</td>';


    echo '<td>';

    echo $days_present;

    echo '</td>';


    echo '<td>';

    echo $days_absent;

    echo '</td>';


    echo '<td>';

    echo number_format(
        $total_hours,
        2
    ) . ' h';

    echo '</td>';


    echo '<td>';

    echo number_format(
        $total_overtime,
        2
    ) . ' h';

    echo '</td>';


    echo '<td>';

    echo number_format(
        $average_hours,
        2
    ) . ' h';

    echo '</td>';


    echo '</tr>';


    echo '</table>';


    echo '<br><br>';
}


/* =====================================================
   PRINTED BY
===================================================== */

echo '<table border="1" width="100%" cellspacing="0" cellpadding="5">';


echo '<tr>';

echo '<td class="footer">Printed By</td>';

echo '<td>';

echo htmlspecialchars(
    $fullname
);

echo '</td>';

echo '</tr>';


echo '<tr>';

echo '<td class="footer">Supervisor ID</td>';

echo '<td>';

echo htmlspecialchars(
    $supervisor_id
);

echo '</td>';

echo '</tr>';


echo '<tr>';

echo '<td class="footer">Date</td>';

echo '<td>';

echo date(
    'd M Y'
);

echo '</td>';

echo '</tr>';


echo '<tr>';

echo '<td class="footer">Time</td>';

echo '<td>';

echo date(
    'h:i A'
);

echo '</td>';

echo '</tr>';


echo '</table>';


echo '</body>';

echo '</html>';

exit();

?>